# Generated by Django 4.2 on 2023-04-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('rate', models.FloatField()),
                ('create_date', models.DateField(auto_now=True)),
                ('modified_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
