# Generated by Django 4.2 on 2023-04-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_commet_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Review',
        ),
    ]
